version: "3"

services:

  discosrv:
    image: ${DOCKER_DISCOSRV_IMAGE_NAME}
    container_name: ${DOCKER_DISCOSRV_HOSTNAME}
    hostname: ${DOCKER_DISCOSRV_HOSTNAME}
    command:
      - "-listen=:8080"
      - "-debug"
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 8080
    volumes:
      - ./discosrv:/var/stdiscosrv/discovery.db:rw
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "https://localhost:8080/ping"]
      interval: 3s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.discosrv-http.entrypoints=http"
      - "traefik.http.routers.discosrv-http.rule=Host(`${DOCKER_DISCOSRV_DOMAIN}`)"
      - "traefik.http.routers.discosrv-http.service=discosrv-backend"

      - "traefik.http.routers.discosrv-https.entrypoints=https"
      - "traefik.http.routers.discosrv-https.tls=true"
      - "traefik.http.routers.discosrv-https.rule=Host(`${DOCKER_DISCOSRV_DOMAIN}`)"
      - "traefik.http.routers.discosrv-https.service=discosrv-backend"

      - "traefik.http.services.discosrv-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.discosrv-backend.loadbalancer.server.port=8384"
    networks:
      - traefik
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  traefik:
    external: true
