version: "3"

services:

  discosrv:
    image: ${DOCKER_DISCOSRV_IMAGE_NAME}
    container_name: ${DOCKER_DISCOSRV_HOSTNAME}
    hostname: ${DOCKER_DISCOSRV_HOSTNAME}
    command:
      - "-listen=:8080"
      - "-debug"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./data:/var/stdiscosrv/discovery.db:rw
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "https://localhost:8080/ping"]
      interval: 3s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1m"